on:
  schedule:
    - cron: '23 2 * * 2'

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
      - name: Install `cargo-outdated`
        run: cargo install cargo-outdated
      - name: Check for necessary updates to `/Cargo.toml`
        run: cargo outdated -R --exit-code 1
